[package]
name = "fireflow-core"
version = { workspace = true }
edition = { workspace = true }
description = """
Core library code for fireflow.
"""

[dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
regex = "1.11.1"
itertools = "0.14.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }