[package]
name = "fireflow-core"
version = { workspace = true }
edition = { workspace = true }
description = """
Core library code for fireflow.
"""

[dependencies]
chrono = { workspace = true }
regex = "1.11.1"
itertools = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
nalgebra = { workspace = true }
polars = { workspace = true }
nonempty = { workspace = true }
once_cell = { version = "1.21.3" }