[workspace]
resolver = "2"
members = [
  "crates/*",
  "pyreflow",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
itertools = "0.14.0"
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }
nonempty = { version = "0.11.0" }
