[package]
name = "fireflow"
version = "0.1.0"
edition = "2024"

[[bin]]
bench = false
path = "crates/fireflow-cli/main.rs"
name = "fireflow"

[dependencies]
clap = { version = "4.5.31" }
fireflow-core = { version = "0.1.0", path = "crates/fireflow-core" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
