[workspace]
resolver = "2"
members = [
  "crates/*",
  "pyreflow",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
pyo3 = { version = "0.24.0", features = ["extension-module", "multiple-pymethods"] }