[package]
name = "fireflow"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
regex = "1.11.1"
itertools = "0.14.0"
clap = { version = "4.5.31" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
