[package]
name = "pyreflow"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "pyreflow"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true }
fireflow-core = { version = "0.1.0", path = "../crates/fireflow-core" }