[package]
name = "pyreflow"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "pyreflow"
crate-type = ["cdylib"]

[dependencies]
fireflow-core = { version = "0.1.0", path = "../crates/fireflow-core" }
pyo3 = { version = "0.23.5", features = ["extension-module", "multiple-pymethods", "chrono"] }
chrono = { workspace = true }